# Generated by Django 4.0 on 2022-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash on Delivery'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], default='Cash on Delivery', max_length=20),
        ),
    ]
