pipeline {
    agent {
        docker {
            image 'python:3.9'
            args '-p 8095:8000'
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r requirements.txt --no-cache-dir'
            }
        }
        stage('Test') {
            steps {
                echo "Tested successfully ..."
            }
        }
        stage('Deliver') {
            steps {
                sh 'python3 manage.py migrate'
                sh 'python3 manage.py collectstatic --no-input'
                sh 'python3 manage.py runserver 0.0.0.0:8000 &' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                // sh 'kill $(lsof -t -i:8000)'
            }
        }
    }
}
