pipeline {
    agent {
        docker {
            image 'python:3.9' // Use a Python Docker image
            args '-p 8000:8000' // Map port 8000 for Django development server
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'pip install -r ecomproject/requirements.txt' // Install Django dependencies
            }
        }
        stage('Test') {
            steps {
                sh 'python manage.py test' // Run Django tests
            }
        }
        stage('Deliver') {
            steps {
                sh 'python manage.py migrate' // Apply database migrations
                sh 'python manage.py collectstatic --no-input' // Collect static files
                sh 'python manage.py runserver 0.0.0.0:8000 &' // Start Django development server in the background
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh 'kill $(lsof -t -i:8000)' // Stop the Django development server
            }
        }
    }
}
